name: Participation Logger

on:
  push:
    branches:
      - main

jobs:
  logging:
    name: Logging another participation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Run changed-files
        uses: tj-actions/changed-files@v1.2.0
        id: changed-files

      - name: Show output
        run: |
          echo "${{ toJSON(steps.changed-files.outputs) }}"
          echo "${{ steps.changed-files.outputs }}"
          echo "${{ github.repository }}"
          echo "${{ toJSON(github.event) }}"
          echo "${{ github.actor }}" 
# { ... }
# Object
# seongbin9786/changed-files
# Object
# seongbin9786
